# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steps', models.IntegerField(default=0, verbose_name='User walk steps')),
            ],
            options={
                'db_table': 'Behavior',
            },
        ),
        migrations.CreateModel(
            name='BloodOxygen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=3, verbose_name='blood oxygen value')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloodpressure', models.IntegerField(verbose_name='blood pressure')),
            ],
            options={
                'db_table': 'BloodPressure',
            },
        ),
        migrations.CreateModel(
            name='BodyTemperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bodytemperature', models.CharField(max_length=128, verbose_name='body temperature')),
            ],
            options={
                'db_table': 'BodyTemperature',
            },
        ),
        migrations.CreateModel(
            name='Breath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breath', models.IntegerField(verbose_name='breath')),
            ],
            options={
                'db_table': 'Breath',
            },
        ),
        migrations.CreateModel(
            name='Glycemia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=3, verbose_name='glycemia')),
            ],
        ),
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heartbeat', models.IntegerField(verbose_name='heart beat counts')),
            ],
            options={
                'db_table': 'HeartBeat',
            },
        ),
        migrations.CreateModel(
            name='IndoorBehavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave', models.BooleanField(default=False, verbose_name='leave or here')),
                ('countleave', models.IntegerField(default=0, verbose_name='how many times leave room today')),
                ('call', models.BooleanField(default=False, verbose_name='Need help now')),
                ('countcall', models.IntegerField(default=0, verbose_name='how many times use call service')),
                ('number', models.CharField(max_length=32, verbose_name='room number')),
                ('room', models.CharField(max_length=128, verbose_name='room title')),
            ],
            options={
                'db_table': 'IndoorBehavior',
            },
        ),
        migrations.CreateModel(
            name='Mattress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('power', models.BooleanField(default=False, verbose_name='mattress no power or not')),
            ],
            options={
                'db_table': 'Mattress',
            },
        ),
        migrations.CreateModel(
            name='UricAcid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=6, verbose_name='uric acid')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=3, verbose_name='User age')),
                ('sex', models.CharField(blank=True, max_length=1, verbose_name='User sex')),
                ('weight', models.CharField(blank=True, max_length=8, verbose_name='User body weight')),
                ('height', models.CharField(blank=True, max_length=8, verbose_name='User height')),
                ('contact', models.CharField(blank=True, max_length=16, verbose_name='User contact number')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='User contact address')),
                ('attend_doctor', models.CharField(blank=True, max_length=128, verbose_name='attend doctor')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Wristband',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('power', models.BooleanField(default=False, verbose_name='wristband no power or not')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User')),
            ],
            options={
                'db_table': 'Wristband',
            },
        ),
        migrations.AddField(
            model_name='uricacid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='indoorbehavior',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='glycemia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='breath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='bodytemperature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='bloodoxygen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
    ]
