# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloodpressure', models.IntegerField(verbose_name='blood pressure')),
            ],
            options={
                'db_table': 'BloodPressure',
            },
        ),
        migrations.CreateModel(
            name='BodyTemperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bodytemperature', models.CharField(max_length=128, verbose_name='body temperature')),
            ],
            options={
                'db_table': 'BodyTemperature',
            },
        ),
        migrations.CreateModel(
            name='Breath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breath', models.IntegerField(verbose_name='breath')),
            ],
            options={
                'db_table': 'Breath',
            },
        ),
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heartbeat', models.IntegerField(verbose_name='heart beat counts')),
            ],
            options={
                'db_table': 'HeartBeat',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='breath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='bodytemperature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
    ]
